# Site settings
title: >
    Research App Landing Page
email: hi@ouremail.com
description: >
    The landing page for our new research app.
baseurl: "/observed-site" # If this site runs in a subdirectory (e.g. /blog/) specify it here.
url: "http://www.[TBD].com" # The base hostname & protocol for your site.

# Build settings
destination: ./www
permalink: pretty

# Content Settings
defaults:
  - 
    # Make all blog posts use the blog layout and define permalink
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
      permalink: "/blog/:title"

sass:
    sass_dir: ./assets/css
    style: :expanded
    
markdown: kramdown