# Site settings
title: >
    Research App Landing Page
email: hi@ouremail.com
description: >
    The landing page for our new research app.
baseurl: "" # If this site runs in a subdirectory (e.g. /blog/) specify it here.
url: "http://www.[TBD].com" # The base hostname & protocol for your site.

defaults:
    # Make all blog posts use the blog layout
    scope:
      path: ""
      type: "posts"
    values:
      layout: blog

# Build settings
destination: ./www
permalink: pretty

sass:
    sass_dir: ./assets/css
    style: :expanded
    
markdown: kramdown